/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Recursos_Tipografias.Fuentes;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import Controlador.ControladorPrimerUso;
import Controlador.Validaciones;
import static Vista.FrmPrimerUsoUsuario.seleccion;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ericksonn
 */
public class FrmPrimerUso extends javax.swing.JFrame {
    Fuentes tipoFuente = new Fuentes();
    public static java.util.Date fecha;
    
    Controlador.ControladorPrimerUso obj = new ControladorPrimerUso();
    Controlador.Validaciones vali = new Validaciones();
    
    FrmNoti2 NInsert = new FrmNoti2();
    FrmNoti3 NDelete = new FrmNoti3();
    FrmNotiError NError = new FrmNotiError();
    LocalDate Fecha = LocalDate.now();
    SimpleDateFormat Formato = new SimpleDateFormat("yyyy-MM-dd"); //Se estable el formato de fehca
    ZoneId systemTimeZone = ZoneId.systemDefault();
    ZonedDateTime zonedDateTime = Fecha.atStartOfDay(systemTimeZone);
    Date FechaActual = Date.from(zonedDateTime.toInstant());
    /**
     * Creates new form fmrPrimeruso
     */
    public FrmPrimerUso() {
        initComponents();
        CargarPais();
        
        lblTituloPrimerUso.setFont(tipoFuente.fuente(tipoFuente.MaxwellBold, 0, 20));
        lblInfo.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        lblNombreEmpresa.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        lblPais.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        lblTelefono.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        lblDescripcion.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        lblNIT.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        lblTipoEmpresa.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        lblDireccionEmpresa.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        txtNombreEmpresa.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        CmbPais.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        txtTelefono.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        txtNIT.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        TPDireccion.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        TADescripcion.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        btnSubir.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 16));
        
        /*Utilizamos new ImageIcon(URL location).getImage() donde el argumento
        *location lo obtenemos a través del método getClass().getResource(String name)
        *que nos devuelve un URL absoluto del recurso que especificamos como String.
        */
        Image icon = new ImageIcon(getClass().getResource("/Recursos_img/E-Dream logo.png")).getImage();
        setIconImage(icon);
        
        btnSubir.setVisible(true);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTituloPrimerUso = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombreEmpresa = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNIT = new javax.swing.JLabel();
        lblDireccionEmpresa = new javax.swing.JLabel();
        lblTipoEmpresa = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TPDireccion = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblInfo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TADescripcion = new javax.swing.JTextArea();
        btnRegistrarse = new org.jdesktop.swingx.JXButton();
        txtTelefono = new javax.swing.JTextField();
        CmbPais = new javax.swing.JComboBox<>();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtNIT = new javax.swing.JTextField();
        FechaFundacion = new com.toedter.calendar.JDateChooser();
        lblAgregarVisualizar = new javax.swing.JLabel();
        btnSubir = new org.jdesktop.swingx.JXButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 222, 216));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 630));

        jPanel1.setBackground(new java.awt.Color(14, 13, 21));

        lblTituloPrimerUso.setForeground(new java.awt.Color(240, 240, 240));
        lblTituloPrimerUso.setText("Primer uso");

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Close.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(lblTituloPrimerUso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(475, 475, 475)
                .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPrimerUso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel2.setBackground(new java.awt.Color(255, 222, 216));
        jPanel2.setLayout(null);

        lblNombreEmpresa.setText("Nombre de la Empresa:");
        jPanel2.add(lblNombreEmpresa);
        lblNombreEmpresa.setBounds(40, 40, 250, 16);

        lblPais.setText("Pais:");
        jPanel2.add(lblPais);
        lblPais.setBounds(40, 110, 170, 16);

        lblTelefono.setText("Numero telefonico Empresarial ");
        jPanel2.add(lblTelefono);
        lblTelefono.setBounds(38, 186, 179, 16);

        lblNIT.setText("NIT:");
        jPanel2.add(lblNIT);
        lblNIT.setBounds(450, 40, 100, 16);

        lblDireccionEmpresa.setText("Direccion Empresarial");
        jPanel2.add(lblDireccionEmpresa);
        lblDireccionEmpresa.setBounds(450, 190, 126, 16);

        lblTipoEmpresa.setText("Año de fundacion");
        jPanel2.add(lblTipoEmpresa);
        lblTipoEmpresa.setBounds(450, 110, 180, 16);

        TPDireccion.setBorder(null);
        jScrollPane6.setViewportView(TPDireccion);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(450, 210, 260, 90);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(40, 320, 720, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(346, 16, 23, 270);

        lblInfo.setText("Informacion de la empresa");
        jPanel2.add(lblInfo);
        lblInfo.setBounds(40, 10, 152, 16);

        lblDescripcion.setText("Descripcion de empresa");
        jPanel2.add(lblDescripcion);
        lblDescripcion.setBounds(40, 340, 139, 16);

        TADescripcion.setColumns(20);
        TADescripcion.setRows(5);
        jScrollPane11.setViewportView(TADescripcion);

        jPanel2.add(jScrollPane11);
        jScrollPane11.setBounds(38, 372, 720, 140);

        btnRegistrarse.setBackground(new java.awt.Color(164, 188, 188));
        btnRegistrarse.setForeground(new java.awt.Color(51, 51, 51));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseExited(evt);
            }
        });
        jPanel2.add(btnRegistrarse);
        btnRegistrarse.setBounds(980, 450, 160, 40);

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono);
        txtTelefono.setBounds(40, 210, 260, 24);

        CmbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(CmbPais);
        CmbPais.setBounds(40, 130, 230, 26);

        txtNombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEmpresaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombreEmpresa);
        txtNombreEmpresa.setBounds(40, 70, 260, 24);

        txtNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNITKeyTyped(evt);
            }
        });
        jPanel2.add(txtNIT);
        txtNIT.setBounds(450, 70, 260, 24);

        FechaFundacion.setDateFormatString("yyyy-MM-dd");
        FechaFundacion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FechaFundacionPropertyChange(evt);
            }
        });
        jPanel2.add(FechaFundacion);
        FechaFundacion.setBounds(450, 130, 260, 29);

        lblAgregarVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/NoImage200px.png"))); // NOI18N
        jPanel2.add(lblAgregarVisualizar);
        lblAgregarVisualizar.setBounds(960, 80, 200, 200);

        btnSubir.setBackground(new java.awt.Color(51, 102, 255));
        btnSubir.setBorder(null);
        btnSubir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Subir.png"))); // NOI18N
        btnSubir.setText("Subir Imagen");
        btnSubir.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSubir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubirMouseExited(evt);
            }
        });
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubir);
        btnSubir.setBounds(990, 310, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(548, 548, 548))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Cargar ComboBox con el Pais
    void CargarPais(){
        DefaultComboBoxModel lista = new DefaultComboBoxModel();
        ResultSet res = Controlador.ControladorPrimerUso.CargarPaisControlador();
        try{
            while(res.next()){
                lista.addElement(res.getString("pais"));
            }
        }catch(Exception e){
            FrmNotiError error = new FrmNotiError();
            error.lblTituloError.setText("Error de Conexión");
            error.TAnotiError.setText("Ocuurio un error en el internet o que los servicios del servidor estén activos");
            error.setVisible(true);
        }
        CmbPais.setModel(lista);
    }
    
    void ObtenerIdPais(){
        try{
            Controlador.ControladorPrimerUso agregar = new Controlador.ControladorPrimerUso();
            agregar.setPaisE(CmbPais.getSelectedIndex());
            ResultSet paisR = ControladorPrimerUso.ObtenerIdPaisControlador();
            if(ControladorPrimerUso.ObtenerIdPaisControlador()!= null){
                int pais = Integer.parseInt(paisR.getString(1));
                agregar.setidPaisE(pais);
            }
        }catch(Exception e){
            
        }
    }
    
    //Método para insertar datos a la Tabla empresa
    void IngresarDatosEmpresa(){
        //Enviando la información a la clase           
            
        if ((obj.validarFecha(FechaFundacion.getDate())) <= 200) {
            System.out.println("Es mayor a 18 años");
        fecha = FechaFundacion.getDate();
        

        Controlador.ControladorPrimerUso agregar = new Controlador.ControladorPrimerUso();
        agregar.setNombreE(txtNombreEmpresa.getText());
        agregar.setNitE(txtNIT.getText());

        SimpleDateFormat Formato = new SimpleDateFormat("yyyy-MM-dd");
        String edad = Formato.format(fecha);

        java.sql.Date FechaInicio = java.sql.Date.valueOf(edad);
        agregar.setAnioFundacionE(FechaInicio);
        agregar.settelefonoEmpresaE(Integer.parseInt(txtTelefono.getText()));
        agregar.setdireccionEmpresaE(TPDireccion.getText());
        ObtenerIdPais();
        
        if(agregar.InsercionPrimerUsoController() == false){
            FrmNotiError error = new FrmNotiError();
            error.lblTituloError.setText("Error de Inserción");
            error.TAnotiError.setText("La empresa no pudo ser ingresada");
            error.setVisible(true);
        }
        else{
            FrmNoti3 notificacion = new FrmNoti3();
            notificacion.lblTituloError.setText("Creación Exitosa");
            notificacion.TANoti3.setText("Empresa creada, empresa ha sido creada con exito");
            FrmPrimerUsoUsuario PrimerUsoUsuario = new FrmPrimerUsoUsuario();
            PrimerUsoUsuario.setVisible(true);
            this.dispose();
        }
        }
    }
    
    public String InsertarImagen(){
        try{
            //Es una clase java que nos permite mostrar fácilmente una ventana para la selección de un fichero
            JFileChooser ventana = new JFileChooser();
            //Se establece un filtro para que solo se muestren archivos con una determinada extensión
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
            //Agregamos el filtro a la ventana que abriremos
            ventana.setFileFilter(filtro);

            int seleccionar = ventana.showOpenDialog(this);
            //Comprobar si se ha dado clic en Aceptar
            if(seleccionar == JFileChooser.APPROVE_OPTION){
                //Convertimos a tipo Archivo el componente seleccionado
                File archivo = ventana.getSelectedFile();
                //Esta función devuelve el nombre de ruta absoluta del objeto de archivo dado.
                seleccion = archivo.getAbsolutePath();
                //Obtenemos el ancho del Label donde la colocaremos
                int ancho = lblAgregarVisualizar.getWidth();
                //Obtenemos la altura del Label donde la colocaremos
                int alto = lblAgregarVisualizar.getHeight();
                //getToolkit Obtiene el kit de herramientas predeterminado y se puede obtener un objeto Toolkit mediante la invocación de este método
                // En este caso nos permite ir a nuestro equipo y obtener la ruta.
                //getImage carga todos los bits de la imagen en la memoria
                Image imagen = getToolkit().getImage(seleccion);
                //Image.SCALE_SMOOTH Elije un algoritmo de escalado de imagen que da mayor prioridad a la suavidad de la imagen que a la velocidad de escalado. 
                imagen = imagen.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                lblAgregarVisualizar.setIcon(new ImageIcon(imagen));
            }
        }
        catch(Exception e){
        
        }
        return seleccion;
    }    
    
    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        //Validamos que los campos no esten vacios
        if (txtNombreEmpresa.getText().trim().equals("")  || txtNIT.getText().trim().equals("") || txtTelefono.getText().trim().equals("") || TPDireccion.getText().trim().equals("") ) {
            FrmNoti1 notificación1 = new FrmNoti1();
            notificación1.lblTituloNoti1.setText("Campos vacios");
            notificación1.TAMensajeError.setText("Todos los campos son requeridos");
            notificación1.setVisible(true);
        }
        else{
            //En caso de que no haya fallos, inserta datos y da paso al siguiente formulario
            IngresarDatosEmpresa();
        }
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseEntered
        btnRegistrarse.setBackground(new Color(51,102,255));
        btnRegistrarse.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegistrarseMouseEntered

    private void btnRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseExited
        btnRegistrarse.setBackground(new Color(164,188,188));
        btnRegistrarse.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_btnRegistrarseMouseExited

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        InsertarImagen();
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnSubirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirMouseExited
        btnSubir.setBackground(new Color(51,102,255));
        btnSubir.setForeground(Color.BLACK);
        btnSubir.setVisible(true);
    }//GEN-LAST:event_btnSubirMouseExited

    private void btnSubirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirMouseEntered
        btnSubir.setBackground(new Color(0,51,102));
        btnSubir.setForeground(Color.white);
    }//GEN-LAST:event_btnSubirMouseEntered

    private void btnSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirMouseClicked
        InsertarImagen();
    }//GEN-LAST:event_btnSubirMouseClicked

    private void FechaFundacionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FechaFundacionPropertyChange
        try {
             
            if (FechaFundacion.getDate() == null) {

            } else {
                if ((obj.validarFecha(FechaFundacion.getDate())) >= 200) {
                    FechaFundacion.setDate(null);
                    
                    NError.TAnotiError.setText("La fecha ingresada debe ser menor o igual a la del día de hoy");
                    NError.lblTituloError.setText("Fecha erronea");
                    NError.setVisible(true);
                } 
                if (FechaFundacion.getDate().before(FechaActual)) {
                    
                }
                else {
                    FechaFundacion.setDate(null);
                    
                    NError.TAnotiError.setText("La fecha ingresada debe ser menor o igual a la del día de hoy");
                    NError.lblTituloError.setText("Fecha erronea");
                    NError.setVisible(true);
                }
            }

        } catch (Exception e) {
            System.out.print("Error Inicio" + e.toString());
        }

    }//GEN-LAST:event_FechaFundacionPropertyChange

    private void txtNombreEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEmpresaKeyTyped
        vali.soloLetras(evt, 2, txtNombreEmpresa.getText());
    }//GEN-LAST:event_txtNombreEmpresaKeyTyped

    private void txtNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyTyped
        vali.soloNumeros(evt, 4, txtNIT.getText());
        vali.Cantidad(evt, txtNIT.getText(), 17);
    }//GEN-LAST:event_txtNITKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        vali.soloNumeros(evt, 1, txtTelefono.getText());
        vali.Cantidad(evt, txtTelefono.getText(), 8);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrimerUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrimerUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrimerUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrimerUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrimerUso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbPais;
    private com.toedter.calendar.JDateChooser FechaFundacion;
    private javax.swing.JTextArea TADescripcion;
    private javax.swing.JTextPane TPDireccion;
    private org.jdesktop.swingx.JXButton btnRegistrarse;
    private org.jdesktop.swingx.JXButton btnSubir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAgregarVisualizar;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDireccionEmpresa;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNIT;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoEmpresa;
    private javax.swing.JLabel lblTituloPrimerUso;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

   
}
