/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;
//Importamos las librerias a utilizar
import Recursos_Tipografias.Fuentes;
import Controlador.RenovarContraseñaController;
import java.awt.Image;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
/**
 *
 * @author Jesus Gerardo
 */
public class FrmRenovarContraseña extends javax.swing.JFrame {
    //Creamos objeto de la clase fuentes
    Fuentes tipoFuente= new Fuentes();
    //Creamos objeto del controlador
    RenovarContraseñaController obj = new RenovarContraseñaController();
    /** Creates new form FrmRenovarContraseña */
    public FrmRenovarContraseña() {
        initComponents();
        lblTituloPrimerUso.setFont(tipoFuente.fuente(tipoFuente.MaxwellBold, 0, 20));
        lblOpps.setFont(tipoFuente.fuente(tipoFuente.MaxwellBold,0,21));
        lblPreocupacion.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,20));
        lblIndicaciones.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,20));
        lblContraseña.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,21));
        lblConfirmar.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,21));
        txtContraseña.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,21));
        txtContraConfirm.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,21));
        btnRegresar.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,21));
        btnRecuperar.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,21));
        lblAvisoContra.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular,0,20));
        lblAvisoContra.setVisible(false);
        //Ejecutamos metodo de cerrar
        CerrarForm();
        
        /*Utilizamos new ImageIcon(URL location).getImage() donde el argumento
        *location lo obtenemos a través del método getClass().getResource(String name)
        *que nos devuelve un URL absoluto del recurso que especificamos como String.
        */
        Image icon = new ImageIcon(getClass().getResource("/Recursos_img/E-Dream logo.png")).getImage();
        setIconImage(icon);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblOpps = new javax.swing.JLabel();
        lblIndicaciones = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblPreocupacion = new javax.swing.JLabel();
        lblIconoContra = new javax.swing.JLabel();
        lblConfirmar = new javax.swing.JLabel();
        lblIconoConfirmar = new javax.swing.JLabel();
        btnRegresar = new org.jdesktop.swingx.JXButton();
        btnRecuperar = new org.jdesktop.swingx.JXButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtContraConfirm = new javax.swing.JPasswordField();
        chbVer = new javax.swing.JCheckBox();
        lblAvisoContra = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTituloPrimerUso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedor.setPreferredSize(new java.awt.Dimension(1090, 620));
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/contrasenarenovada.png"))); // NOI18N
        pnlContenedor.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        lblOpps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOpps.setText("¡Opps! Olvidaste tu contraseña");
        pnlContenedor.add(lblOpps, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        lblIndicaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIndicaciones.setText("Ingresa tu nueva contraseña y luego confirma dicha contraseña para renovar");
        pnlContenedor.add(lblIndicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContraseña.setText("Ingresa la nueva contraseña:");
        pnlContenedor.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 240, -1));

        lblPreocupacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPreocupacion.setText("No te preocupes te ayudaremos solo llena la siguiente información");
        pnlContenedor.add(lblPreocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        lblIconoContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/contrasena104px.png"))); // NOI18N
        pnlContenedor.add(lblIconoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        lblConfirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConfirmar.setText("Confirma contraseña:");
        pnlContenedor.add(lblConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 220, 20));

        lblIconoConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/contrasena104px.png"))); // NOI18N
        pnlContenedor.add(lblIconoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        btnRegresar.setBorder(null);
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/RegresarLogin.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlContenedor.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 140, -1));

        btnRecuperar.setBackground(new java.awt.Color(255, 255, 255));
        btnRecuperar.setBorder(new org.jdesktop.swingx.border.IconBorder());
        btnRecuperar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Recover50px.png"))); // NOI18N
        btnRecuperar.setText("Renovar");
        btnRecuperar.setBorderPainted(false);
        btnRecuperar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRecuperar.setOpaque(false);
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });
        pnlContenedor.add(btnRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 480, 150, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyReleased(evt);
            }
        });
        pnlContenedor.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 190, -1));

        txtContraConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraConfirmKeyReleased(evt);
            }
        });
        pnlContenedor.add(txtContraConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 190, -1));

        chbVer.setText("Mostrar Contraseña");
        chbVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbVerMouseClicked(evt);
            }
        });
        chbVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbVerActionPerformed(evt);
            }
        });
        pnlContenedor.add(chbVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, -1, -1));

        lblAvisoContra.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoContra.setText("¡La contraseña no coincide!");
        pnlContenedor.add(lblAvisoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, -1, -1));

        jPanel1.setBackground(new java.awt.Color(14, 13, 21));

        lblTituloPrimerUso.setForeground(new java.awt.Color(240, 240, 240));
        lblTituloPrimerUso.setText("Recuperar Contraseña");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(lblTituloPrimerUso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPrimerUso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContenedor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/ImagenLogin-m.png"))); // NOI18N
        pnlContenedor.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 630));

        getContentPane().add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmCancelarRecuperacion cancelar = new FrmCancelarRecuperacion();
        cancelar.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        //Comprobamos que ambos textbox contengan la misma contraseña
        if (lblAvisoContra.isVisible()) {
            FrmNotiError error = new FrmNotiError();
            error.TAnotiError.setText("¡Error, las contraseñas no coinciden! Verifique que ambos contraseñas coincidan");
            error.setVisible(true);
        }else{
            //Obtenemos la contraseña del textbox
            String contraseña=new String(txtContraConfirm.getPassword());
            //Ejecutamos el metodo que actualiza la contraseña enviando como parametro la contraseña
            boolean confirm=obj.actualizarContra(contraseña);
            //Si hay erro
            if (confirm==false) {
                FrmNotiError error = new FrmNotiError();
                error.TAnotiError.setText("¡Error! No se ha podido actualizar la contraseña");
                error.setVisible(true);
            }else{
                //Si no hay error
                FrmNoti1 noti1 = new FrmNoti1();
                noti1.lblTituloNoti1.setText("¡Felicidades!");
                noti1.TAMensajeError.setText("¡Felicidades!Has completado el proceso de renovación de contraseña, ¡Tu contraseña esta actualizada!");
                noti1.setVisible(true);
                FrmLogin login = new FrmLogin();
                login.setVisible(true);
                dispose();
            }
        }      
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void chbVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbVerMouseClicked
        // TODO add your handling code here:
        if (chbVer.isSelected()) {
            txtContraseña.setEchoChar((char)0);
            txtContraConfirm.setEchoChar((char)0);
        }else{
            txtContraseña.setEchoChar('*');
            txtContraConfirm.setEchoChar('*');
        }
    }//GEN-LAST:event_chbVerMouseClicked

    private void chbVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbVerActionPerformed

    private void txtContraConfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraConfirmKeyReleased
        // TODO add your handling code here:
        //Comprobamos que la contraseña igual sea la misma en ambos textfield
        //Creamos variable String que guarde los campos
        String contra=new String(txtContraseña.getPassword());
        String contrac=new String(txtContraConfirm.getPassword());
        boolean confirm=obj.contraIgual(contra,contrac);
        if (confirm==true) {
            lblAvisoContra.setVisible(false);
        }else{
            lblAvisoContra.setVisible(true);
        }
    }//GEN-LAST:event_txtContraConfirmKeyReleased

    private void txtContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyReleased
        // TODO add your handling code here:
        //Comprobamos que la contraseña igual sea la misma en ambos textfield
        //Creamos variable String que guarde los campos
        String contra=new String(txtContraseña.getPassword());
        String contrac=new String(txtContraConfirm.getPassword());
        boolean confirm=obj.contraIgual(contra,contrac);
        if (confirm==true) {
            lblAvisoContra.setVisible(false);
        }else{
            lblAvisoContra.setVisible(true);
        }
    }//GEN-LAST:event_txtContraseñaKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked
    //Creamos metodo que cierre el form 
    void CerrarForm(){
        //Creamos objeto de timpo Timer
        Timer tiempo = new Timer();
        //Creamos la tarea a realizar
        TimerTask habilitar = new TimerTask() {
            @Override
            public void run() {
                //Evaluamos si la variable en el controlador es diferente a cero lo que significa que se debe cerrar
                if (obj.getCerrar()>0) {
                    cancel();
//                    obj.setCerrar(0);
                    dispose();
                    obj.setCerrar(0);
                }
            }
        };
        tiempo.schedule(habilitar, 0, 100);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRenovarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRenovarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRenovarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRenovarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRenovarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnRecuperar;
    private org.jdesktop.swingx.JXButton btnRegresar;
    private javax.swing.JCheckBox chbVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvisoContra;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIconoConfirmar;
    private javax.swing.JLabel lblIconoContra;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIndicaciones;
    private javax.swing.JLabel lblOpps;
    private javax.swing.JLabel lblPreocupacion;
    private javax.swing.JLabel lblTituloPrimerUso;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPasswordField txtContraConfirm;
    private javax.swing.JPasswordField txtContraseña;
    // End of variables declaration//GEN-END:variables

}
