/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorReportes;
import Controlador.ControladorVariables;
import Modelo.Conexion;
import Recursos_Tipografias.Fuentes;
import java.awt.Color;
import java.net.URLDecoder;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ericksonn
 */
public class FrmReportes extends javax.swing.JPanel {

    Fuentes f = new Fuentes();

    //Colores Modo Night
    Color Piel = new Color(255,222,212);
    Color Morado = new Color(94,45,79);
    Color Oscuro = new Color(14,13,21);
    //Colores Modo Light
    Color AzulOscuro = new Color(33, 47, 74);
    Color Celeste = new Color(61, 111, 137);

    ControladorVariables variables = new ControladorVariables();
    ControladorReportes obj = new ControladorReportes();

    public FrmReportes() {
        initComponents();
        Colores();
        MostrarDatos();
        lblTitulo.setFont(f.fuente(f.MaxwellBold, 0, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTReporte = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 222, 216));
        setMaximumSize(new java.awt.Dimension(1090, 620));
        setMinimumSize(new java.awt.Dimension(1090, 620));
        setPreferredSize(new java.awt.Dimension(1090, 620));

        PanelContenedor.setBackground(new java.awt.Color(255, 222, 212));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Imprimir 30px.png"))); // NOI18N
        jButton2.setText("Imprimir reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(14, 13, 21));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Reportes");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(518, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(520, 520, 520))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Cantidad rentado"
            }
        ));
        jScrollPane1.setViewportView(jTReporte);

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(15, 15, 15))
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void MostrarDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = Controlador.ControladorReportes.CargarTablaController();
        modelo.setColumnIdentifiers(new Object[]{"Nombre", "Cantidad rentado"});
        try {
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("nombreProducto"), rs.getInt("RENTADO")});
            }
            jTReporte.setModel(modelo);
        } catch (Exception e) {
        }
    }

    void Colores(){
        ControladorVariables variables = new ControladorVariables();
        switch(variables.getColor()){
            case 1://Oscuro
                PanelContenedor.setBackground(Piel);
                jPanel2.setBackground(Oscuro);
                break;
            case 2://Claro
                PanelContenedor.setBackground(Color.white);
                jPanel2.setBackground(AzulOscuro);
                break;
            default:
                PanelContenedor.setBackground(Piel);
                jPanel2.setBackground(Oscuro);
                break;
        }        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path = "";
        String ruta = "";
        //Obtenemos empresa y empleado para mandarlos como parametri
        String usuario = variables.getUsuario();
        int idEmpleado = variables.getEmpleado();
        String empresaE = obj.CargarNombreEmpresa(idEmpleado);
        System.out.println(empresaE);
        //System.out.println(res.getString(res.getString(empleado)));

        try {

            // String nombreEmpresa = res.getString("em.nombreEmpresa");
            path = getClass().getResource("/Reportes/Renta.jasper").getPath();
            ruta = getClass().getResource("/Reportes/prueba.jasper").getPath();

            System.out.println(path);
            //Se decodifica por algun caracter especial
            path = URLDecoder.decode(path, "UTF-8");
            ruta = URLDecoder.decode(ruta, "UTF-8");
            //Se crea la conexion
            Connection cn = new Conexion().Conexion();
            //Se rea los prametros
            Map parametros = new HashMap();
            // parametros.clear();
            //el nombre que se dio al parametro en JasperReport fue "p1", y se debe llamar desde Java con
            //ese mismo nombre, a su lado se pasa el valor del parametro
            parametros.put("Empresa", empresaE);
            parametros.put("Usuario", usuario);
            //Se crea el objeto de reporte
            JasperReport reporte = (JasperReport) JRLoader.loadObject(path);
            JasperReport reporte2 = (JasperReport) JRLoader.loadObject(ruta);
            //Se crea el objeto impresion de reporte
            JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
            JasperPrint imprimir2 = JasperFillManager.fillReport(reporte2, parametros, cn);
            //Ahora e crea el vior donde e muestra el reporte
            JasperViewer visor = new JasperViewer(imprimir, false);//False es para dispose
            JasperViewer visor2 = new JasperViewer(imprimir2, false);
            visor.setTitle("Reporte de productos rentados");
            visor.setVisible(true);
            visor2.setTitle("Reporte de productos vendidos");
            visor2.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTReporte;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
