/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControladorVariables;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Recursos_Tipografias.Fuentes;
import java.awt.Color;

/**
 *
 * @author Ericksonn
 */
public class FrmSobreNosotros extends javax.swing.JPanel {

    Fuentes tipoFuente = new Fuentes();
    //Colores Modo Night
    Color Piel = new Color(255,222,212);
    Color Morado = new Color(94,45,79);
    Color Oscuro = new Color(14,13,21);
    //Colores Modo Light
    Color AzulOscuro = new Color(33, 47, 74);
    Color Celeste = new Color(61, 111, 137);
    
    public FrmSobreNosotros() {
        initComponents();
        Colores();
        TAJesus.setBackground(new Color (0,0,0,0));
        TAErick.setBackground(new Color (0,0,0,0));
        TALenny.setBackground(new Color (0,0,0,0));
        TASey.setBackground(new Color (0,0,0,0));
        TAOliver.setBackground(new Color (0,0,0,0));
        
        TAErick.setText("\n \"El miedo se transforma en \n      fuerza y la fuerza en \nconocimiento, el conocimiento\n        en experiencia y la\n      experiencia en poder\"");
        TAJesus.setText("\n\n  \"No busques el tesoro en\n           otro citio, porque\n             tu ya eres uno\"");
        TALenny.setText("      \"Pueden existir muchos \nentornos, muchos lenguajes,\n pero siempre te identificaras\n                   con uno.\n          Así es en la vida,\n                así es en\n            programación.\"");
        TAOliver.setText("\n\n \"La felicidad no es algo que\n se pospone para el futuro;\n es algo que se diseña para\n               el presente\"");
        TASey.setText("\n    \"Elige un trabajo que te\n     apasione y no volverás a\n    trabajar ni un solo día de\n                  tu vida\n");
         
        TAErick.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 15));
        TAJesus.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 15));
        TALenny.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 15));
        TASey.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 15));
        TAOliver.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 0, 15));
        lblSey.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 1, 14));
        lblOliver.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 1, 14));
        lblJesus.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 1, 14));
        lblLenny.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 1, 14));
        lblErick.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 1, 14));
        lblTituloNosotros.setFont(tipoFuente.fuente(tipoFuente.MaxwellBold, 1, 15));
        lblDesarrolladores.setFont(tipoFuente.fuente(tipoFuente.MaxwellRegular, 1, 14));
    }

    void Colores(){
        ControladorVariables variables = new ControladorVariables();
        switch(variables.getColor()){
            case 1://Oscuro
                JPCentral.setBackground(Piel);
                JPTitulo.setBackground(Oscuro);
                break;
            case 2://Claro
                JPCentral.setBackground(Color.white);
                JPTitulo.setBackground(Celeste);
                break;
            default:
                JPCentral.setBackground(Piel);
                JPTitulo.setBackground(Oscuro);
                break;
        }        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPTitulo = new javax.swing.JPanel();
        lblTituloNosotros = new javax.swing.JLabel();
        JPCentral = new javax.swing.JPanel();
        lblDesarrolladores = new javax.swing.JLabel();
        lblSey = new javax.swing.JLabel();
        lblOliver = new javax.swing.JLabel();
        lblJesus = new javax.swing.JLabel();
        lblLenny = new javax.swing.JLabel();
        lblErick = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TAErick = new javax.swing.JTextArea();
        TALenny = new javax.swing.JTextArea();
        TASey = new javax.swing.JTextArea();
        TAOliver = new javax.swing.JTextArea();
        TAJesus = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(1090, 620));
        setMinimumSize(new java.awt.Dimension(1090, 620));

        JPTitulo.setBackground(new java.awt.Color(14, 13, 21));

        lblTituloNosotros.setForeground(new java.awt.Color(240, 240, 240));
        lblTituloNosotros.setText("Nosotros somos");

        javax.swing.GroupLayout JPTituloLayout = new javax.swing.GroupLayout(JPTitulo);
        JPTitulo.setLayout(JPTituloLayout);
        JPTituloLayout.setHorizontalGroup(
            JPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTituloLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(lblTituloNosotros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPTituloLayout.setVerticalGroup(
            JPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPTituloLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblTituloNosotros)
                .addGap(15, 15, 15))
        );

        JPCentral.setBackground(new java.awt.Color(255, 222, 216));

        lblDesarrolladores.setText("Nuestros desarrolladores somos:");

        lblSey.setText("Sey Alvarado");

        lblOliver.setText("Oliver Erazo");

        lblJesus.setText("Jesus Esquivel");

        lblLenny.setText("Lenny Elias");

        lblErick.setText("Erick Chinchilla");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Lenny.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Sey.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Erick.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Oliver.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_img/Jesús.png"))); // NOI18N

        TAErick.setEditable(false);
        TAErick.setColumns(20);
        TAErick.setRows(5);
        TAErick.setText("Erick");

        TALenny.setEditable(false);
        TALenny.setColumns(20);
        TALenny.setRows(5);
        TALenny.setText("Lenny");

        TASey.setEditable(false);
        TASey.setColumns(20);
        TASey.setRows(5);
        TASey.setText("Sey");

        TAOliver.setEditable(false);
        TAOliver.setColumns(20);
        TAOliver.setRows(5);
        TAOliver.setText("Oliver");

        TAJesus.setEditable(false);
        TAJesus.setColumns(20);
        TAJesus.setRows(5);
        TAJesus.setText("Jesús");

        javax.swing.GroupLayout JPCentralLayout = new javax.swing.GroupLayout(JPCentral);
        JPCentral.setLayout(JPCentralLayout);
        JPCentralLayout.setHorizontalGroup(
            JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCentralLayout.createSequentialGroup()
                .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(TAErick, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblErick)))
                .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TASey, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblSey)))
                .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(TAOliver, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblOliver)))
                .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(TALenny, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(TAJesus, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPCentralLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblLenny)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblJesus)
                        .addGap(71, 71, 71))
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(JPCentralLayout.createSequentialGroup()
                .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(lblDesarrolladores)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPCentralLayout.setVerticalGroup(
            JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDesarrolladores)
                .addGap(9, 9, 9)
                .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPCentralLayout.createSequentialGroup()
                        .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLenny)
                            .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblJesus)
                                .addComponent(lblOliver)
                                .addComponent(lblSey))))
                    .addGroup(JPCentralLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblErick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(JPCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TAErick, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TASey, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAOliver, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAJesus, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TALenny, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(491, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(JPTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(JPCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(JPCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPCentral;
    private javax.swing.JPanel JPTitulo;
    private javax.swing.JTextArea TAErick;
    private javax.swing.JTextArea TAJesus;
    private javax.swing.JTextArea TALenny;
    private javax.swing.JTextArea TAOliver;
    private javax.swing.JTextArea TASey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDesarrolladores;
    private javax.swing.JLabel lblErick;
    private javax.swing.JLabel lblJesus;
    private javax.swing.JLabel lblLenny;
    private javax.swing.JLabel lblOliver;
    private javax.swing.JLabel lblSey;
    private javax.swing.JLabel lblTituloNosotros;
    // End of variables declaration//GEN-END:variables
}
